name: Release App

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2

      - id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.event.repository.name }}

      - name: Get current time
        uses: MyJetTools/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD HH:mm:ss
          utcOffset: "+00:00"

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF_NAME})
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CFD_REGISTRY_USER }}
          password: ${{ secrets.CFD_REGISTRY_PASSWORD }}
          registry: ${{ secrets.CFD_REGISTRY_HOST }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.CFD_REGISTRY_HOST }}/cfd/${{ steps.string.outputs.lowercase }}:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            app_name=${{ steps.string.outputs.lowercase }}
            app_version=${{ steps.get_version.outputs.VERSION }}
            app_compilation_date=${{ steps.current-time.outputs.formattedTime }}


  update_version_master:
    timeout-minutes: 10
    needs: 
    - test
    - build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Extract branch name
      uses: vazco/github-actions-branch-name@v1
      id: branch
  
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF_NAME})

    - id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.event.repository.name }}

    - name: get master kube yamls
      uses: actions/checkout@v2
      with:
        repository: my-cfd-platform/kubernates-infrastructure
        ref: uat
        token: ${{ secrets.CFD_GIT_TOKEN }}
    - run: ls
    - run: sed -i "s|${{ secrets.CFD_REGISTRY_HOST }}/cfd/${{ steps.string.outputs.lowercase }}:.*|${{ secrets.CFD_REGISTRY_HOST }}/cfd/${{ steps.string.outputs.lowercase }}:${{ steps.get_version.outputs.VERSION }}|g" ./services/${{ steps.string.outputs.lowercase }}/deployment.*
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -a -m "Update version ${{ steps.get_version.outputs.VERSION }} of service ${{ steps.string.outputs.lowercase }} on UAT"
        git push

    - uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.CFD_KUBE_CONFIG_UAT }}
        context: kubernetes-uat
    
    - uses: azure/k8s-deploy@v3.1
      with:
        manifests: |
          ./services/${{ steps.string.outputs.lowercase }}
        namespace: simple-trading